

trash_items = [
    # Weapons
    "Rusty Dagger",
    "Chipped Short Sword",
    "Cracked Wooden Staff",
    "Bent Iron Dagger",
    "Blunt Wooden Club",
    "Rusty Shortsword",
    "Worn Wooden Bow",
    "Broken Crossbow",
    "Frayed Whip",
    "Crude Stone Axe",
    "Tarnished Cutlass",
    "Splintered Longbow",
    "Dull Cleaver",
    "Ragged Spear",
    "Worn-out Mace",
    "Rusty Hand Axe",
    "Patched Leather Whip",
    "Twisted Knuckles",
    "Fractured Shiv",
    "Blunt Throwing Knives",
    "Rusted Warhammer",
    "Dented Helmet",
    "Tattered Chainmail",
    "Ragged Tunic",
    "Patchy Leather Armor"
    
    # Armor
    "Worn-out Cloth Hood",
    "Threadbare Robe",
    "Tattered Cloth Gloves",
    "Cracked Leather Boots",
    "Rusty Chainmail Coif",
    "Ragged Leather Vest",
    "Frayed Pants",
    "Broken Buckler",
    "Worn-out Cloth Shoes",
    "Tattered Cloak",
    "Patched Leather Leggings",
    "Rusty Chainmail Gauntlets",
    "Ragged Leather Bracers",
    "Worn-out Cloth Belt",
    "Tattered Cloth Shoulderpads",
    "Dented Helmet",
    "Tattered Chainmail",
    "Ragged Tunic",
    "Patchy Leather Armor",
    "Fractured Greaves",
    "Tarnished Pauldrons",
    "Cracked Leather Helmet",
    "Rusty Chainmail Leggings",
    "Threadbare Boots"
]

common_items = [
    # Weapons
    "Iron Dagger",
    "Steel Short Sword",
    "Oak Staff",
    "Iron Shortsword",
    "Reinforced Wooden Club",
    "Steel Longsword",
    "Hunting Bow",
    "Crossbow",
    "Leather Whip",
    "Stone Axe",
    "Steel Cutlass",
    "Longbow",
    "Steel Cleaver",
    "Iron Spear",
    "Spiked Mace",
    "Battle Axe",
    "Studded Leather Whip",
    "Brass Knuckles",
    "Steel Shiv",
    "Throwing Knives",
    "Iron Warhammer",
    "Steel Katana",
    "Iron Helmet",
    "Chainmail",
    "Leather Armor",
    
    # Armor
    "Cloth Hood",
    "Woolen Robe",
    "Leather Gloves",
    "Leather Boots",
    "Chainmail Coif",
    "Leather Vest",
    "Canvas Pants",
    "Round Shield",
    "Cloth Shoes",
    "Cloth Cloak",
    "Leather Leggings",
    "Chainmail Gauntlets",
    "Leather Bracers",
    "Cloth Belt",
    "Shoulder Pads",
    "Steel Helmet",
    "Chainmail Leggings",
    "Padded Tunic",
    "Leather Armor",
    "Steel Greaves",
    "Steel Pauldrons",
    "Leather Helmet",
    "Chainmail Leggings",
    "Sturdy Boots"
]

uncommon_items = [
    # Weapons
    "Fine Steel Dagger",
    "Tempered Steel Short Sword",
    "Enchanted Oak Staff",
    "Fine Steel Shortsword",
    "Reinforced Iron Club",
    "Fine Steel Longsword",
    "Composite Bow",
    "Improved Crossbow",
    "Whip of Precision",
    "Obsidian Axe",
    "Fine Steel Cutlass",
    "Elven Longbow",
    "Fine Steel Cleaver",
    "Steel-tipped Spear",
    "War Mace",
    "Dwarven Battle Axe",
    "Reinforced Leather Whip",
    "Silver Knuckles",
    "Fine Steel Shiv",
    "Precision Throwing Knives",
    "Dwarven Warhammer",
    "Katana of the Ronin",
    "Reinforced Iron Helmet",
    "Steel Chainmail",
    "Hardened Leather Armor",
    
    # Armor
    "Silk Hood",
    "Elven Silk Robe",
    "Reinforced Leather Gloves",
    "Reinforced Leather Boots",
    "Tempered Chain Coif",
    "Studded Leather Vest",
    "Fine Cloth Pants",
    "Reinforced Shield",
    "Reinforced Cloth Shoes",
    "Elven Cloak",
    "Reinforced Leather Leggings",
    "Tempered Chain Gauntlets",
    "Reinforced Leather Bracers",
    "Sturdy Cloth Belt",
    "Reinforced Shoulder Pads",
    "Tempered Steel Helmet",
    "Steel Chainmail Leggings",
    "Reinforced Leather Tunic",
    "Studded Leather Armor",
    "Tempered Steel Greaves",
    "Tempered Steel Pauldrons",
    "Reinforced Leather Helmet",
    "Tempered Chain Leggings",
    "Enchanted Boots"
]

rare_items = [
    # Weapons
    "Masterwork Steel Dagger",
    "Runed Steel Short Sword",
    "Staff of the Arcanist",
    "Masterwork Steel Shortsword",
    "Adamantine Club",
    "Masterwork Steel Longsword",
    "Elven Composite Bow",
    "Crossbow of Precision",
    "Whip of the Serpent",
    "Mithril Axe",
    "Masterwork Steel Cutlass",
    "Dragonbone Longbow",
    "Masterwork Steel Cleaver",
    "Venom-tipped Spear",
    "Hammer of Thunder",
    "Legendary Battle Axe",
    "Dragonhide Whip",
    "Ethereal Gauntlets",
    "Masterwork Steel Shiv",
    "Assassin's Throwing Knives",
    "Warhammer of the Titans",
    "Blade of Eternal Darkness",
    "Adamantine Helmet",
    "Adamantine Chainmail",
    "Dragonhide Armor",
    
    # Armor
    "Elven Silk Hood",
    "Robe of the Archmage",
    "Enchanted Leather Gloves",
    "Boots of the Ranger",
    "Adamantine Chain Coif",
    "Dragonscale Vest",
    "Silk Pants of Agility",
    "Tower Shield of Protection",
    "Elven Boots of Swiftness",
    "Cloak of Invisibility",
    "Dragonscale Leggings",
    "Adamantine Gauntlets",
    "Reinforced Dragonhide Bracers",
    "Belt of Strength",
    "Pauldrons of the Guardian",
    "Helmet of the Berserker",
    "Adamantine Chain Leggings",
    "Dragonhide Tunic",
    "Dragonscale Armor",
    "Adamantine Greaves",
    "Adamantine Pauldrons",
    "Dragonbone Helmet",
    "Adamantine Chain Leggings",
    "Boots of the Windwalker"
]

epic_items = [
    # Weapons
    "Soulblade of Annihilation",
    "Excalibur, the Legendary Sword",
    "Staff of the Archmagi",
    "Blade of the Phoenix",
    "Hammer of the Titans",
    "Dragonbone Longbow of the Wyrm",
    "Scepter of the Eternal Emperor",
    "Eldritch Crossbow of Doom",
    "Whip of the Abyssal Serpent",
    "Axe of the Celestial Guardian",
    "Dagger of Shadows",
    "Bow of the Elven Kings",
    "Glaive of the Eternal Sentinel",
    "Mace of Divine Retribution",
    "Halberd of the Reaper",
    "Sword of the Seraphim",
    "Warhammer of the Ancient Kings",
    "Frostreaver, the Ice Blade",
    "Venomstrike Bow",
    "Thunderfury, Blessed Blade of the Windseeker",
    "Soulstealer, the Cursed Blade",
    "Staff of the Grand Archmage",
    "Blade of the Forgotten Hero",
    "Scepter of the Celestial Court",
    "Doombringer, the Dark Sword",
    
    # Armor
    "Helm of the Divine Protector",
    "Armor of the Phoenix",
    "Robes of the Archmagi",
    "Breastplate of the Celestial Guardian",
    "Dragonbone Plate Mail",
    "Cloak of Shadows",
    "Boots of the Eternal Traveler",
    "Shield of the Ancients",
    "Cloak of the Elven Lords",
    "Gauntlets of the Fallen King",
    "Helm of the Abyssal Champion",
    "Legplates of the Valiant Defender",
    "Bracers of the Seraphim",
    "Belt of the Stormlord",
    "Pauldrons of the Eternal Watcher",
    "Crown of the Celestial Monarch",
    "Legguards of the Eternal Sentinel",
    "Plate Mail of the Holy Crusader",
    "Dragonscale Armor of the Wyrm",
    "Greaves of the Forgotten Hero",
    "Pauldrons of the Vanquisher",
    "Helmet of the Dark Conqueror",
    "Legplates of the Ancient Kings",
    "Boots of the Shadow Assassin"
]

legendary_items = [
    # Weapons
    "Excalibur, the Sword of Kings",
    "Frostmourne, the Runeblade of the Lich King",
    "Thunderfury, Blessed Blade of the Windseeker",
    "Ashbringer, the Blade of the Scarlet Highlord",
    "Atiesh, Greatstaff of the Guardian",
    "Warglaive of Azzinoth",
    "Sulfuras, Hand of Ragnaros",
    "Shadowmourne, the Axe of the Lich King",
    "Gorehowl, Axe of the Warsong Chieftain",
    "The Twin Blades of Azzinoth",
    "The Ashbringer",
    "The Fangs of the Father",
    "The Kingslayers",
    "The Hammer of Purification",
    "The Stars' Fury",
    "The Lightning Bolt",
    "The Celestial Defender",
    "The Soulrender",
    "The Voidreaver",
    "The Arcane Annihilator",
    "The Eternal Fire",
    "The Grand Inquisitor",
    "The Cosmic Cleaver",
    "The Mythic Maul",
    "The Immortal Blade",
    
    # Armor
    "Helmet of the World Breaker",
    "Breastplate of the Celestial Champion",
    "Robes of the Archdruid",
    "Crown of the Firelord",
    "The Burning Halo",
    "The Eternal Crown",
    "The Wings of Freedom",
    "The Frostforged Armor",
    "The Enigmatic Cloak",
    "The Gauntlets of Justice",
    "The Leggings of the Celestial Watcher",
    "The Pauldrons of the Divine Protector",
    "The Shield of Aegis",
    "The Embrace of the Seraphim",
    "The Belt of Divine Power",
    "The Radiant Greaves",
    "The Mantle of the Celestial Guardian",
    "The Plate Mail of the Holy Avenger",
    "The Dragonbone Helm",
    "The Wyrmplate",
    "The Eternal Boots",
    "The Shadowcloak",
    "The Arcane Robes",
    "The Mantle of Darkness",
    "The Helm of the Fallen Hero"
]

void_touched_items = [
    # Weapons
    "Voidblade of the Abyss",
    "Whispering Bow of Shadows",
    "Eclipse Staff of Dark Omens",
    "Nightmare Dagger",
    "Voidcaster, the Scepter of Despair",
    "Shadowreaper Scythe",
    "Dreadbow of the Void",
    "Soulshard Crossbow",
    "Abyssal Whip of Torment",
    "Voidforged Axe of Oblivion",
    "Doombringer Longsword",
    "Darkened Cleaver of the Fallen",
    "Shadowstrike Spear",
    "Cursed Mace of Eternal Agony",
    "Twilight Warhammer",
    "Void Katana of Chaos",
    "Corrupted Knuckles",
    "Soulreaver Shiv",
    "Shadowthrower Knives",
    "Voidrender Warhammer",
    "Desolate Greatsword",
    "Voidfire Battle Axe",
    "Whispering Helm of the Forsaken",
    "Eclipse Plate of Dread",
    "Nightfall Chainmail",
    
    # Armor
    "Hood of Eternal Shadows",
    "Robes of the Void Prophet",
    "Cloak of Eternal Twilight",
    "Gloves of the Voidwalker",
    "Boots of the Abyssal Watcher",
    "Mask of Desolation",
    "Vestments of the Voidcaller",
    "Shroud of the Abyss",
    "Gauntlets of Endless Nightmares",
    "Greaves of the Shadowed Abyss",
    "Shoulderpads of Eternal Darkness",
    "Voidforged Bracers",
    "Belt of Shadowed Souls",
    "Legplates of the Void Champion",
    "Chestguard of the Nether",
    "Helm of the Darkened Depths",
    "Chainmail of the Twisted Void",
    "Voidforged Armor",
    "Voidblessed Greaves",
    "Cloak of the Void Warden",
    "Twilight Veil",
    "Voidtouched Mantle",
    "Abyssal Crown",
    "Nightfall Legguards",
    "Eclipse Boots"
]

blessed_items = [
    # Weapons
    "Blade of Divine Light",
    "Holy Avenger, the Sword of Justice",
    "Staff of Radiant Blessings",
    "Scepter of the High Priest",
    "Bow of Heavenly Grace",
    "Seraphic Crossbow",
    "Mace of Holy Retribution",
    "Warhammer of the Crusader",
    "Sword of the Archangel",
    "Hammer of the Righteous",
    "Heavenly Longbow",
    "Divine Cleaver",
    "Spear of Divine Judgment",
    "Blessed Flail",
    "Celestial Glaive",
    "Sacred Katana",
    "Lightbringer's Knuckles",
    "Divine Shiv",
    "Angelic Throwing Knives",
    "Holy Warhammer",
    "Radiant Greatsword",
    "Blessed Battle Axe",
    "Cleansing Hammer",
    "Sword of the Celestial Guardian",
    "Purifier's Dagger",
    
    # Armor
    "Helm of Radiant Glory",
    "Breastplate of Holy Protection",
    "Robes of the High Priest",
    "Crown of Divine Grace",
    "Heavenly Halo",
    "Aegis of the Divine",
    "Wings of the Seraphim",
    "Gauntlets of the Blessed Paladin",
    "Greaves of the Holy Crusader",
    "Boots of Sacred Ground",
    "Pauldrons of Angelic Might",
    "Bracers of Divine Intervention",
    "Belt of Heavenly Strength",
    "Legplates of the Virtuous",
    "Plate Mail of the Righteous",
    "Helm of the Divine Champion",
    "Chainmail of Celestial Protection",
    "Blessed Armor",
    "Gauntlets of the Archangel",
    "Greaves of Radiant Justice",
    "Cloak of Divine Guidance",
    "Wings of Redemption",
    "Crown of the Celestial Monarch",
    "Legguards of the Holy Defender",
    "Boots of the Divine Guardian"
]

demonic_items = [
    # Weapons
    "Infernal Blade",
    "Doombringer, the Darkened Sword",
    "Staff of Infernal Torment",
    "Scepter of the Demonic Overlord",
    "Hellfire Bow",
    "Soulreaper Crossbow",
    "Mace of Demonic Fury",
    "Warhammer of Hellfire",
    "Blade of the Demon King",
    "Axe of Annihilation",
    "Dagger of Shadowflame",
    "Bow of the Inferno",
    "Glaive of the Dark Legion",
    "Hammer of Damnation",
    "Sword of the Infernal Lord",
    "Felblade, the Corrupted Katana",
    "Hellforged Knuckles",
    "Infernal Shiv",
    "Soulflame Throwing Knives",
    "Doomhammer, the Cursed Mace",
    "Darkbane Greatsword",
    "Demonforged Battle Axe",
    "Skullcrusher, the Demonic Hammer",
    "Blade of Eternal Darkness",
    "Cursed Dagger of the Abyss",
    
    # Armor
    "Helm of Infernal Wrath",
    "Breastplate of Demonic Power",
    "Robes of the Dark Sorcerer",
    "Crown of Hellfire",
    "Fiendish Halo",
    "Demonic Aegis",
    "Wings of the Inferno",
    "Gauntlets of Demonic Dominion",
    "Greaves of the Infernal Conqueror",
    "Boots of the Shadowed Abyss",
    "Pauldrons of Demon's Might",
    "Bracers of Dark Descent",
    "Belt of Infernal Strength",
    "Legplates of the Diabolic",
    "Plate Mail of Infernal Fury",
    "Helm of the Demon Prince",
    "Chainmail of Demonic Domination",
    "Demonic Armor",
    "Gauntlets of the Dark Overlord",
    "Greaves of Hellish Retribution",
    "Cloak of Infernal Shadows",
    "Wings of Damnation",
    "Crown of the Abyssal King",
    "Legguards of the Fiendish Destroyer",
    "Boots of the Infernal Legion"
]

divine_items = [
    # Weapons
    "Sword of the Divine Champion",
    "Holy Avenger, the Blade of Virtue",
    "Staff of Celestial Blessings",
    "Scepter of the Holy Emperor",
    "Bow of the Archangel",
    "Heavenly Crossbow",
    "Mace of Divine Justice",
    "Warhammer of the Angelic Host",
    "Blade of the Seraph",
    "Axe of Divinity",
    "Dagger of the Divine Assassin",
    "Bow of the Celestial Guardians",
    "Glaive of the Celestial Sentinel",
    "Hammer of the Archons",
    "Sword of the High Seraphim",
    "Katana of Heavenly Light",
    "Knuckles of Divine Fury",
    "Shiv of Holy Retribution",
    "Throwing Knives of the Divine",
    "Hammer of the Divine Crusader",
    "Greatsword of the Divine Protector",
    "Battle Axe of Celestial Might",
    "Hammer of Divine Wrath",
    "Blade of Eternal Radiance",
    "Dagger of the Archangel",
    
    # Armor
    "Helm of Divine Grace",
    "Breastplate of the Holy Crusader",
    "Robes of the Divine Archmage",
    "Crown of Celestial Glory",
    "Radiant Halo",
    "Divine Aegis",
    "Wings of the Seraphim",
    "Gauntlets of the Divine Champion",
    "Greaves of the Celestial Guardian",
    "Boots of the Heavenly Path",
    "Pauldrons of Angelic Fury",
    "Bracers of Divine Protection",
    "Belt of Celestial Strength",
    "Legplates of the Divine",
    "Plate Mail of the Holy Avatar",
    "Helm of the Archangel",
    "Chainmail of Divine Providence",
    "Divine Armor",
    "Gauntlets of the Holy Paladin",
    "Greaves of Radiant Justice",
    "Cloak of Celestial Guidance",
    "Wings of Redemption",
    "Crown of the Divine Monarch",
    "Legguards of the Celestial Defender",
    "Boots of the Divine Guardian"
]

cosmical_items = [
    # Weapons
    "Cosmic Blade of Infinity",
    "Starshard Staff of the Cosmos",
    "Ethereal Scepter of the Astral Plane",
    "Galactic Bow of Celestial Harmony",
    "Nova Crossbow of Cosmic Power",
    "Nebula Mace of Eternal Light",
    "Quasar Warhammer of the Void",
    "Supernova Sword of the Celestial Emperor",
    "Singularity Axe of the Cosmic Guardian",
    "Infinity Dagger of the Astral Assassin",
    "Black Hole Bow of Infinite Space",
    "Dark Matter Glaive of the Galactic Guardian",
    "Cosmic Hammer of Creation",
    "Stellar Katana of Eternal Radiance",
    "Aurora Knuckles of Cosmic Fury",
    "Celestial Shiv of the Astral Wanderer",
    "Comet Throwing Knives of the Starborn",
    "Eclipse Warhammer of the Voidwalker",
    "Galaxy Greatsword of Cosmic Might",
    "Nebula Battle Axe of the Starforged",
    "Supernova Scythe of the Cosmic Reaver",
    "Quasar Lance of Celestial Judgment",
    "Voidstorm Blade of Infinite Chaos",
    "Starlight Dagger of the Astral Mage",
    "Ethereal Bow of the Celestial Archer",
    
    # Armor
    "Cosmic Helm of Astral Protection",
    "Starshard Breastplate of Celestial Radiance",
    "Ethereal Robes of the Cosmic Sage",
    "Galactic Crown of Eternal Light",
    "Nova Halo of Cosmic Harmony",
    "Nebula Aegis of the Astral Guardian",
    "Quasar Wings of Celestial Flight",
    "Supernova Gauntlets of the Cosmic Warrior",
    "Singularity Greaves of Infinite Space",
    "Infinity Boots of the Astral Wanderer",
    "Black Hole Pauldrons of Eternal Darkness",
    "Dark Matter Bracers of the Galactic Protector",
    "Cosmic Belt of Astral Power",
    "Stellar Legplates of Celestial Might",
    "Aurora Plate Mail of Cosmic Fury",
    "Celestial Helm of the Starborn",
    "Comet Chainmail of Infinite Space",
    "Eclipse Armor of Celestial Harmony",
    "Galaxy Armor of Eternal Radiance",
    "Nebula Helm of the Astral Sentinel",
    "Supernova Greaves of Cosmic Power",
    "Quasar Pauldrons of the Celestial Defender",
    "Voidstorm Cloak of Infinite Chaos",
    "Starlight Cape of the Astral Mage",
    "Ethereal Boots of the Celestial Voyager"
]

multiversal_items = [
    # Weapons
    "Omniscient Blade of the Multiverse",
    "Eternal Staff of All Realms",
    "Cosmic Scepter of Infinite Creation",
    "Interdimensional Bow of Omnifinality",
    "Transcendent Crossbow of Boundless Potential",
    "Universal Mace of Eternal Existence",
    "Panuniversal Warhammer of Cosmic Balance",
    "Infinite Sword of the Omniverse",
    "All-Knowing Axe of Multiversal Dominion",
    "Eternity Dagger of Boundless Knowledge",
    "Infinity Bow of Universal Harmony",
    "Transcendental Glaive of Cosmic Order",
    "Omnipotent Hammer of Infinite Power",
    "Endless Katana of Eternal Enlightenment",
    "Dimensional Knuckles of Universal Unity",
    "Infinite Shiv of Omniversal Enlightenment",
    "Multiversal Throwing Knives of Endless Possibility",
    "Eternal Warhammer of Panuniversal Might",
    "Cosmic Greatsword of Infinite Realms",
    "Interstellar Battle Axe of the Multiverse",
    "Omnipresent Scythe of Cosmic Destiny",
    "Universal Lance of Infinite Potential",
    "Voidcrusher Blade of Omniversal Chaos",
    "Omniscient Dagger of All-Knowing",
    "Interdimensional Bow of Transcendence",
    
    # Armor
    "Omnipotent Helm of Infinite Wisdom",
    "Eternal Breastplate of Multiversal Protection",
    "Cosmic Robes of Boundless Enlightenment",
    "Interstellar Crown of Universal Sovereignty",
    "Transcendent Halo of Omniscience",
    "Universal Aegis of Eternal Harmony",
    "Panuniversal Wings of Cosmic Flight",
    "Infinite Gauntlets of Interdimensional Power",
    "All-Knowing Greaves of Multiversal Unity",
    "Eternity Boots of Omniversal Destiny",
    "Infinity Pauldrons of Universal Order",
    "Transcendental Bracers of Cosmic Balance",
    "Omnipresent Belt of Infinite Potential",
    "Endless Legplates of Eternal Existence",
    "Dimensional Plate Mail of Universal Authority",
    "Infinite Helm of Panuniversal Enlightenment",
    "Cosmic Chainmail of Multiversal Harmony",
    "Interstellar Armor of Eternal Balance",
    "Omnipotent Helm of Infinite Wisdom",
    "Eternal Breastplate of Multiversal Protection",
    "Cosmic Robes of Boundless Enlightenment",
    "Interstellar Crown of Universal Sovereignty",
    "Transcendent Halo of Omniscience",
    "Universal Aegis of Eternal Harmony",
    "Panuniversal Wings of Cosmic Flight",
]